// AUTO-GENERATED by the MagicMinds grade+export pass. Single source of truth for photography.
// Grade: variant B (warm/vibrant, one-film). All 24 graded; ungraded originals never ship.
// Consumed by the Picture primitive (Packet 2). Do NOT hand-edit widths/dominant; re-run the pass.
// NOTE: sources are low-res portrait (~950-1010px). See ASSET-FLAGS.md.

export type PhotoAssetId =
  | 'mm-bluey-detail-sensory-01'
  | 'mm-bluey-detail-sensory-02'
  | 'mm-bluey-hero-environment-01'
  | 'mm-bluey-play-ballpit-01'
  | 'mm-bluey-setup-garden-01'
  | 'mm-bluey-station-adopt-01'
  | 'mm-gingerbread-candid-toddler-01'
  | 'mm-gingerbread-detail-centerpiece-01'
  | 'mm-gingerbread-setup-houses-01'
  | 'mm-grinch-backdrop-delilah-01'
  | 'mm-grinch-character-photo-01'
  | 'mm-halloween-candid-craft-01'
  | 'mm-halloween-candid-plush-01'
  | 'mm-halloween-station-plush-01'
  | 'mm-kidchella-hero-table-01'
  | 'mm-kidchella-setup-bracelets-01'
  | 'mm-kidchella-wide-lawn-01'
  | 'mm-monster-play-ballpit-01'
  | 'mm-monster-setup-carwash-01'
  | 'mm-patriotic-hero-environment-01'
  | 'mm-patriotic-setup-table-01'
  | 'mm-toystory-detail-canvas-01'
  | 'mm-toystory-detail-costume-01'
  | 'mm-toystory-setup-easels-01';

export type PhotoFormat = 'avif' | 'webp' | 'jpg';

export interface PhotoAsset {
  id: PhotoAssetId;
  alt: string;                 // meaningful, required
  theme: string;
  type: string;
  width: number;               // native (largest shipped) width, px
  height: number;              // native height, px
  aspectRatio: number;         // width / height of the MASTER (portrait ~0.76-0.84)
  widths: number[];            // shipped srcset widths (never upscaled beyond native)
  formats: PhotoFormat[];      // avif primary, webp, jpg fallback
  dominant: string;            // hex LQIP placeholder background
  priority?: 'lcp';            // only the Scene-4 hero
  graded: true;
}

// Path convention: /assets/photos/graded/{id}-{width}.{format}
export const PHOTO_BASE = '/assets/photos/graded';

export const photos: Record<PhotoAssetId, PhotoAsset> = {
  'mm-bluey-detail-sensory-01': {
    id: 'mm-bluey-detail-sensory-01',
    alt: "A Bluey sensory and craft table with rolling pins, play-dough and a Bingo cutout.",
    theme: 'bluey',
    type: 'detail',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#888C4A',
    graded: true,
  },
  'mm-bluey-detail-sensory-02': {
    id: 'mm-bluey-detail-sensory-02',
    alt: "A held-up Bluey beach sensory bin with Bluey and Bingo cutouts and a bounce house behind.",
    theme: 'bluey',
    type: 'detail',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#869062',
    graded: true,
  },
  'mm-bluey-hero-environment-01': {
    id: 'mm-bluey-hero-environment-01',
    alt: "A full Bluey backyard setup: balloon garland, kids\u2019 table, bounce castle, ball pit and character cutouts.",
    theme: 'bluey',
    type: 'hero',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#8D8C4B',
    priority: 'lcp',
    graded: true,
  },
  'mm-bluey-play-ballpit-01': {
    id: 'mm-bluey-play-ballpit-01',
    alt: "A personalized \u201cWackadoo! Eddie is One\u201d Bluey ball pit with slides and a white bounce castle.",
    theme: 'bluey',
    type: 'play',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#CEC5AD',
    graded: true,
  },
  'mm-bluey-setup-garden-01': {
    id: 'mm-bluey-setup-garden-01',
    alt: "A Bluey craft table with chiavari chairs, a balloon garland and a bounce house behind.",
    theme: 'bluey',
    type: 'setup',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#9FA06F',
    graded: true,
  },
  'mm-bluey-station-adopt-01': {
    id: 'mm-bluey-station-adopt-01',
    alt: "An \u201cAdopt Bluey & Bingo\u201d stuff-a-plush shelf with a stuffing machine and adoption certificate.",
    theme: 'bluey',
    type: 'station',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#AB9F86',
    graded: true,
  },
  'mm-gingerbread-candid-toddler-01': {
    id: 'mm-gingerbread-candid-toddler-01',
    alt: "A toddler in red decorating a gingerbread house at a holiday craft table.",
    theme: 'gingerbread',
    type: 'candid',
    width: 980, height: 1232, aspectRatio: 0.7955,
    widths: [640, 980],
    formats: ['avif','webp','jpg'],
    dominant: '#C58B7F',
    graded: true,
  },
  'mm-gingerbread-detail-centerpiece-01': {
    id: 'mm-gingerbread-detail-centerpiece-01',
    alt: "A gingerbread train and house centerpiece with Santa and gingerbread figures.",
    theme: 'gingerbread',
    type: 'detail',
    width: 980, height: 1232, aspectRatio: 0.7955,
    widths: [640, 980],
    formats: ['avif','webp','jpg'],
    dominant: '#D1A39A',
    graded: true,
  },
  'mm-gingerbread-setup-houses-01': {
    id: 'mm-gingerbread-setup-houses-01',
    alt: "A row of decorated gingerbread houses lined up indoors.",
    theme: 'gingerbread',
    type: 'setup',
    width: 980, height: 1232, aspectRatio: 0.7955,
    widths: [640, 980],
    formats: ['avif','webp','jpg'],
    dominant: '#DDB5A5',
    graded: true,
  },
  'mm-grinch-backdrop-delilah-01': {
    id: 'mm-grinch-backdrop-delilah-01',
    alt: "A personalized \u201cDelilah Turns Three\u201d Grinch balloon backdrop with a dessert table.",
    theme: 'grinch',
    type: 'backdrop',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#C77956',
    graded: true,
  },
  'mm-grinch-character-photo-01': {
    id: 'mm-grinch-character-photo-01',
    alt: "A costumed Grinch holding a child at a \u201cGrinchmas Pictures\u201d balloon backdrop.",
    theme: 'grinch',
    type: 'character',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#AE834F',
    graded: true,
  },
  'mm-halloween-candid-craft-01': {
    id: 'mm-halloween-candid-craft-01',
    alt: "Children making crafts at a Halloween table with a pumpkin-cat plush and a child in a witch hat.",
    theme: 'halloween',
    type: 'candid',
    width: 980, height: 1232, aspectRatio: 0.7955,
    widths: [640, 980],
    formats: ['avif','webp','jpg'],
    dominant: '#A46566',
    graded: true,
  },
  'mm-halloween-candid-plush-01': {
    id: 'mm-halloween-candid-plush-01',
    alt: "Two girls stuffing a black-cat plush at a Halloween station, a bounce dome behind them.",
    theme: 'halloween',
    type: 'candid',
    width: 980, height: 1232, aspectRatio: 0.7955,
    widths: [640, 980],
    formats: ['avif','webp','jpg'],
    dominant: '#7F7968',
    graded: true,
  },
  'mm-halloween-station-plush-01': {
    id: 'mm-halloween-station-plush-01',
    alt: "A Halloween stuff-a-plush shelf of pumpkins, cats and bats with a girl in a star tutu.",
    theme: 'halloween',
    type: 'station',
    width: 980, height: 1232, aspectRatio: 0.7955,
    widths: [640, 980],
    formats: ['avif','webp','jpg'],
    dominant: '#927654',
    graded: true,
  },
  'mm-kidchella-hero-table-01': {
    id: 'mm-kidchella-hero-table-01',
    alt: "A \u201cKidchella\u201d public activation table with pink chairs and a sequined runner at a lifestyle center.",
    theme: 'kidchella',
    type: 'hero',
    width: 1008, height: 1204, aspectRatio: 0.8372,
    widths: [640, 1008],
    formats: ['avif','webp','jpg'],
    dominant: '#AB977E',
    graded: true,
  },
  'mm-kidchella-setup-bracelets-01': {
    id: 'mm-kidchella-setup-bracelets-01',
    alt: "A Kidchella bracelet and bead making table with pink chairs and a MagicMinds sign.",
    theme: 'kidchella',
    type: 'setup',
    width: 1008, height: 1204, aspectRatio: 0.8372,
    widths: [640, 1008],
    formats: ['avif','webp','jpg'],
    dominant: '#92826A',
    graded: true,
  },
  'mm-kidchella-wide-lawn-01': {
    id: 'mm-kidchella-wide-lawn-01',
    alt: "A wide view of the Kidchella activation on a lawn with pink chairs and storefronts behind.",
    theme: 'kidchella',
    type: 'wide',
    width: 1008, height: 1204, aspectRatio: 0.8372,
    widths: [640, 1008],
    formats: ['avif','webp','jpg'],
    dominant: '#A48470',
    graded: true,
  },
  'mm-monster-play-ballpit-01': {
    id: 'mm-monster-play-ballpit-01',
    alt: "A monster-truck \u201cPit Party\u201d ball pit with dual slides and a balloon arch.",
    theme: 'monster',
    type: 'play',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#969067',
    graded: true,
  },
  'mm-monster-setup-carwash-01': {
    id: 'mm-monster-setup-carwash-01',
    alt: "A monster-truck \u201cCar Wash\u201d activity table with checkered linen and a balloon garland.",
    theme: 'monster',
    type: 'setup',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#6C745B',
    graded: true,
  },
  'mm-patriotic-hero-environment-01': {
    id: 'mm-patriotic-hero-environment-01',
    alt: "A patriotic party backyard with a white bounce castle and red-gingham round tables on a lawn.",
    theme: 'patriotic',
    type: 'hero',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#666B31',
    graded: true,
  },
  'mm-patriotic-setup-table-01': {
    id: 'mm-patriotic-setup-table-01',
    alt: "A July-4th kids\u2019 table with blue chairs, star linen and red-white-and-blue tassel garland.",
    theme: 'patriotic',
    type: 'setup',
    width: 952, height: 1288, aspectRatio: 0.7391,
    widths: [640, 952],
    formats: ['avif','webp','jpg'],
    dominant: '#4B4C2E',
    graded: true,
  },
  'mm-toystory-detail-canvas-01': {
    id: 'mm-toystory-detail-canvas-01',
    alt: "A Buzz Lightyear line-art canvas on an easel beside a piggy bank and paint palette at a Toy Story craft station.",
    theme: 'toystory',
    type: 'detail',
    width: 980, height: 1232, aspectRatio: 0.7955,
    widths: [640, 980],
    formats: ['avif','webp','jpg'],
    dominant: '#EBD7AF',
    graded: true,
  },
  'mm-toystory-detail-costume-01': {
    id: 'mm-toystory-detail-costume-01',
    alt: "Felt Buzz, Woody and Jessie costume vests with red cowboy hats and craft supply bins.",
    theme: 'toystory',
    type: 'detail',
    width: 980, height: 1232, aspectRatio: 0.7955,
    widths: [640, 980],
    formats: ['avif','webp','jpg'],
    dominant: '#DDB984',
    graded: true,
  },
  'mm-toystory-setup-easels-01': {
    id: 'mm-toystory-setup-easels-01',
    alt: "Woody and Jessie paint-your-own canvases on easels beside a \u201cYou\u2019ve got a friend in me\u201d sign.",
    theme: 'toystory',
    type: 'setup',
    width: 980, height: 1232, aspectRatio: 0.7955,
    widths: [640, 980],
    formats: ['avif','webp','jpg'],
    dominant: '#D8BCA0',
    graded: true,
  },
};

export const photoList: PhotoAsset[] = Object.values(photos);
