/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as AdventuresSlugRouteImport } from './routes/adventures.$slug'
import { Route as WorldsSlugRouteImport } from './routes/worlds.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventuresSlugRoute = AdventuresSlugRouteImport.update({
  id: '/adventures/$slug',
  path: '/adventures/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsSlugRoute = WorldsSlugRouteImport.update({
  id: '/worlds/$slug',
  path: '/worlds/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/process': typeof ProcessRoute
  '/adventures/$slug': typeof AdventuresSlugRoute
  '/worlds/$slug': typeof WorldsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/process': typeof ProcessRoute
  '/adventures/$slug': typeof AdventuresSlugRoute
  '/worlds/$slug': typeof WorldsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/create': typeof CreateRoute
  '/process': typeof ProcessRoute
  '/adventures/$slug': typeof AdventuresSlugRoute
  '/worlds/$slug': typeof WorldsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/create'
    | '/process'
    | '/adventures/$slug'
    | '/worlds/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/create'
    | '/process'
    | '/adventures/$slug'
    | '/worlds/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/create'
    | '/process'
    | '/adventures/$slug'
    | '/worlds/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateRoute: typeof CreateRoute
  ProcessRoute: typeof ProcessRoute
  AdventuresSlugRoute: typeof AdventuresSlugRoute
  WorldsSlugRoute: typeof WorldsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventures/$slug': {
      id: '/adventures/$slug'
      path: '/adventures/$slug'
      fullPath: '/adventures/$slug'
      preLoaderRoute: typeof AdventuresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds/$slug': {
      id: '/worlds/$slug'
      path: '/worlds/$slug'
      fullPath: '/worlds/$slug'
      preLoaderRoute: typeof WorldsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateRoute: CreateRoute,
  ProcessRoute: ProcessRoute,
  AdventuresSlugRoute: AdventuresSlugRoute,
  WorldsSlugRoute: WorldsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
